export enum LodgingQueryParams {
    Limit = 'Limit',
    Offset = 'Offset',
    City = 'City',
    Name = 'Name',
    IncludeImages = 'IncludeImages',
    RatingAtLeast = 'RatingAtLeast',
    SearchRadius = 'SearchRadius',
    BedsAtLeast = 'BedsAtLeast',
    BedRoomsAtLeast = 'BedRoomsAtLeast',
    BathsAtLeast = 'BathsAtLeast',
    HasBedType = 'HasBedType',
    HasAmenity = 'HasAmenity',
    SortOrder = 'SortOrder',
    SortKey = 'SortKey',
}
